sudo: required

os: linux

language: c

compiler: gcc

env:
  global:
    - PACKAGE_TOP=$HOME/package
    - BOOST_DIR=$PACKAGE_TOP/boost/1.63.0
    - YAML_CPP_DIR=$PACKAGE_TOP/yaml-cpp/yaml-cpp-0.5.3
    - PYTHON_DIR=$PACKAGE_TOP/python/3.6.1

before_install:
    - mkdir -p $BOOST_DIR
    - mkdir -p $YAML_CPP_DIR
    - mkdir -p $PYTHON_DIR

install:
    # install python 3.6.1
    - cd $PYTHON_DIR
    - wget -O Python-3.6.1.tgz https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tgz
    - tar xzf Python-3.6.1.tgz --strip 1
    - ./configure
    - make
    - make install

    # Install boost
    - cd $BOOST_DIR
    - wget -O boost_1_63_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz/download
    - tar xzf boost_1_63_0.tar.gz --strip 1
    - ./bootstrap.sh
    - travis_wait ./b2 -d0
    - ./b2 install

    # Install YAML-CPP
    - cd $YAML_CPP_DIR
    - wget -O yaml-cpp-0.5.3.tar.gz https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.5.3.tar.gz
    - tar zxf yaml-cpp-0.5.3.tar.gz --strip 1
    - mkdir build; cd build
    - cmake ..
    - make
    - make install

before_script:
    # Prepare config.mak file
    - |
      cat <<EOF > config.mak
      HARCH=linux-x86_64
      ARCHES +=
      USE_CXX11_default=NO
      INSTALL_DIR=/usr/local/cpsw
      EOF

script:
    - make
